//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalProgramSetting
    {
        public int SettingId { get; set; }
        public string ExcelStartingCell { get; set; }
        public Nullable<bool> IsSummarizeLimit { get; set; }
    }
}
