//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeBudgetEntities : DbContext
    {
        public HomeBudgetEntities()
            : base("name=HomeBudgetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<GlobalProgramSetting> GlobalProgramSettings { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
        public virtual DbSet<OutcomeLimit> OutcomeLimits { get; set; }
        public virtual DbSet<PeriodicalIncome> PeriodicalIncomes { get; set; }
        public virtual DbSet<PeriodicalOutcome> PeriodicalOutcomes { get; set; }
    }
}
