//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IncomeID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public bool IsPernament { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime IncomeDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
