//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutcomeLimit
    {
        public int OutcomeLimitID { get; set; }
        public decimal Limit { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsSum { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
