//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodicalIncome
    {
        public int PeriodicalIncomeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Period { get; set; }
        public System.DateTime LastEntryDate { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LastIncomeID { get; set; }
    }
}
